/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <quackmore-ff@yahoo.com> wrote this file.  As long as you retain this notice
 * you can do whatever you want with this stuff. If we meet some day, and you 
 * think this stuff is worth it, you can buy me a beer in return. Quackmore
 * ----------------------------------------------------------------------------
 */

#ifndef __ESPBOT_RELEASE_H__
#define __ESPBOT_RELEASE_H__

/*
 *  ESPBOT_RELEASE is coming from git
 *  'git --no-pager describe --tags --always --dirty'
 *  and is generated by the Makefile
 *  the following avoid warning generation by Visual Code
 */

#ifndef ESPBOT_RELEASE
#define ESPBOT_RELEASE "Unavailable"
#endif

#endif